/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package library_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ESHA
 */
public class addAdmin extends javax.swing.JInternalFrame implements commoninterface{

    /**
     * Creates new form addAdmin
     */
    public addAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Create Admin");
        getContentPane().setLayout(null);

        jButton1.setText("Create Admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 200, 114, 23);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 70, 86, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 110, 86, 14);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 150, 130, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 70, 120, 20);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(180, 110, 120, 20);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(180, 150, 120, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\java\\library_system\\images\\project\\background-learner.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-490, -330, 1050, 670);

        setBounds(0, 0, 417, 335);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!jTextField1.getText().equals("") && !jPasswordField1.getText().equals(""))
        {
            if(jPasswordField1.getText().equals(jPasswordField2.getText()))
            {
                try
                {
                    Connection myconnection=DriverManager.getConnection(path+place,uname,password);
                    try
                    {
                        String q="insert into atable values(?,?)";
                        PreparedStatement mystatement=myconnection.prepareStatement(q);
                        mystatement.setString(1, jTextField1.getText());
                        mystatement.setString(2, jPasswordField1.getText());
                        if(mystatement.executeUpdate()>0)
                        {
                            JOptionPane.showMessageDialog(null, "Admin Created Successfully");

                        }
                        jTextField1.setText("");
                        jPasswordField1.setText("");
                        jPasswordField2.setText("");

                    }
                    catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null, "Error Establishing Query " + e.getMessage());
                    }
                    finally
                    {
                        myconnection.close();
                    }
                }
                catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null, "Error Establishing Connection " + e.getMessage());
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Password does not match.");
                jPasswordField1.setText("");
                jPasswordField2.setText("");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please enter valid username and password");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
