/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package library_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ESHA
 */
public class adminFine extends javax.swing.JInternalFrame implements commoninterface{

    /**
     * Creates new form adminFine
     */
    public adminFine() {
        initComponents();
        
        try
        {
            Connection myconnection=DriverManager.getConnection(path+place,uname,password);
            try
            {
                DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
                String q="select * from utable where fine!=0";
                PreparedStatement mystatement=myconnection.prepareStatement(q);
                ResultSet myresult=mystatement.executeQuery();
                String appname1,appid1;
                long fine1;
                mymodel.setRowCount(0);
                if(myresult.next())
                {
                    do
                    {
                        appname1=myresult.getString("name");
                        appid1=myresult.getString("id");
                        fine1=myresult.getLong("fine");
                        mymodel.addRow(new Object[]{appname1,appid1,fine1});
                    }while(myresult.next());
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"No such applicants found.");
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error Establishing Query " + e.getMessage());
            }
            finally
            {
                myconnection.close();
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error Establishing Connection " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Fine Due");
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Applicant Name", "Applicant Id", "Fine"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 41, 550, 370);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\java\\library_system\\images\\project\\165642597.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-60, -10, 700, 500);

        setBounds(0, 0, 632, 511);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
