/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package library_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static library_system.commoninterface.password;
import static library_system.commoninterface.path;
import static library_system.commoninterface.place;
import static library_system.commoninterface.uname;

/**
 *
 * @author ESHA
 */
public class availableBooks extends javax.swing.JInternalFrame implements commoninterface{

    /**
     * Creates new form displayAllBooks
     */
    public availableBooks() {
        initComponents();
        try
       {
           Connection myconnection=DriverManager.getConnection(path+place,uname,password);
           
           
                try
                {

                    DefaultTableModel mymodel=(DefaultTableModel)jTable2.getModel();
                    String q="select * from books where issued=0";
                    PreparedStatement mystatement=myconnection.prepareStatement(q);
                    ResultSet myresult=mystatement.executeQuery();
                    mymodel.setRowCount(0);
                    if(myresult.next())
                    {
                        do
                        {    String name1,bookid1,author1,publisher1;
                             name1=myresult.getString("name");
                             bookid1=myresult.getString("book_id");
                             author1=myresult.getString("author");
                             publisher1=myresult.getString("publisher");
                             mymodel.addRow(new Object[]{name1,bookid1,author1,publisher1});
                        }while(myresult.next());
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "No Books Found");   
                    }          
                }
                catch(Exception e)
                {
                       JOptionPane.showMessageDialog(rootPane, "Error Establishing Query " + e.getMessage());
                }
                finally
                {
                       myconnection.close();
                }   
           
       }
       catch(SQLException e)
       {
             JOptionPane.showMessageDialog(rootPane, "Error Establishing Connection " + e.getMessage());
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("List of all available Books");
        getContentPane().setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Name", "Book Id", "Author", "Pubisher"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 42, 550, 360);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\java\\library_system\\images\\project\\165642597.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-70, -70, 710, 590);

        setBounds(0, 0, 632, 490);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
