/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package library_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ESHA
 */
public class checkForAvailability extends javax.swing.JInternalFrame implements commoninterface{

    /**
     * Creates new form searchBook
     */
    public checkForAvailability() {
        initComponents();
        jButton2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Check for Availability");
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Name", "Book Id", "Author", "Publisher"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 57, 522, 355);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(110, 20, 189, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 70, 17);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(324, 23, 100, 23);

        jButton2.setText("Check");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(538, 57, 90, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\java\\library_system\\images\\project\\background_5.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-40, 0, 710, 430);

        setBounds(0, 0, 652, 453);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
       {
           Connection myconnection=DriverManager.getConnection(path+place,uname,password);
           if(!jTextField1.getText().equals(""))
           {
                try
                {

                    DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
                    String q="select * from books where name like ?";
                    PreparedStatement mystatement=myconnection.prepareStatement(q);
                    mystatement.setString(1, "%"+jTextField1.getText()+"%");
                    ResultSet myresult=mystatement.executeQuery();
                    mymodel.setRowCount(0);
                    if(myresult.next())
                    {
                        do
                        {    String name1,bookid1,author1,publisher1;
                             name1=myresult.getString("name");
                             bookid1=myresult.getString("book_id");
                             author1=myresult.getString("author");
                             publisher1=myresult.getString("publisher");
                      
                             mymodel.addRow(new Object[]{name1,bookid1,author1,publisher1});
                        }while(myresult.next());
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "Name does not exist.");
                        jTextField1.setText("");
                        
                    }          
                }
                catch(Exception e)
                {
                       JOptionPane.showMessageDialog(rootPane, "Error Establishing Query " + e.getMessage());
                }
                finally
                {
                       myconnection.close();
                }   
           }
           else
           {
               JOptionPane.showMessageDialog(rootPane, "Enter a valid name");
           }
       }
       catch(SQLException e)
       {
             JOptionPane.showMessageDialog(rootPane, "Error Establishing Connection " + e.getMessage());
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jButton2.setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row=jTable1.getSelectedRow();
        int col=1;
        String regno=jTable1.getValueAt(row, col).toString();
        try
       {
           Connection myconnection=DriverManager.getConnection(path+place,uname,password);
           try
           {
               String q="select * from books where book_id=?";
               PreparedStatement mystatement=myconnection.prepareStatement(q);
               mystatement.setString(1, regno);
               ResultSet myresult=mystatement.executeQuery();
               if(myresult.next())
               {
                   int check=myresult.getInt("issued");
                   if(check==1)
                   {
                       JOptionPane.showMessageDialog(rootPane, "This book is not available");
                   }
                   else
                   {
                       JOptionPane.showMessageDialog(rootPane,"This book is available");
                   }
               }
               else
               {
                   JOptionPane.showMessageDialog(rootPane, "Book Id does not exist");
                   jTextField1.setText("");
               }          
           }
           catch(Exception e)
           {
                  JOptionPane.showMessageDialog(rootPane, "Error Establishing Query " + e.getMessage());
           }
           finally
           {
                  myconnection.close();
           }   
       }
       catch(SQLException e)
       {
             JOptionPane.showMessageDialog(rootPane, "Error Establishing Connection " + e.getMessage());
       }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
