/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package library_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static library_system.commoninterface.password;
import static library_system.commoninterface.path;
import static library_system.commoninterface.place;
import static library_system.commoninterface.uname;

/**
 *
 * @author ESHA
 */
public class displayUsers extends javax.swing.JInternalFrame implements commoninterface{

    /**
     * Creates new form displayAllBooks
     */
    public displayUsers() {
        initComponents();
        try
       {
           Connection myconnection=DriverManager.getConnection(path+place,uname,password);
           
           
                try
                {

                    DefaultTableModel mymodel=(DefaultTableModel)jTable2.getModel();
                    String q="select * from utable";
                    PreparedStatement mystatement=myconnection.prepareStatement(q);
                    ResultSet myresult=mystatement.executeQuery();
                    mymodel.setRowCount(0);
                    if(myresult.next())
                    {
                        do
                        {    String name1,id1,uname1,gender1,dob1,email1;
                             name1=myresult.getString("name");
                             id1=myresult.getString("id");
                             uname1=myresult.getString("uname");
                             gender1=myresult.getString("gender");
                             dob1=myresult.getString("dob");
                             email1=myresult.getString("email");
                             mymodel.addRow(new Object[]{name1,id1,uname1,gender1,dob1,email1});
                        }while(myresult.next());
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "No Users Found");   
                    }          
                }
                catch(Exception e)
                {
                       JOptionPane.showMessageDialog(rootPane, "Error Establishing Query " + e.getMessage());
                }
                finally
                {
                       myconnection.close();
                }   
           
       }
       catch(SQLException e)
       {
             JOptionPane.showMessageDialog(rootPane, "Error Establishing Connection " + e.getMessage());
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("All Users");
        getContentPane().setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Id", "Username", "Gender", "Date of Birth", "Email Id"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 50, 630, 402);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\java\\library_system\\images\\project\\165642597.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, -20, 1080, 570);

        setBounds(0, 0, 709, 579);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
