/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package library_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ESHA
 */
public class resetPasswordUser extends javax.swing.JInternalFrame implements commoninterface{

    /**
     * Creates new form resetPassword
     */
    public resetPasswordUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Reset Password");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 86, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Current Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 140, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 140, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirm New Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 180, 14);

        jPasswordField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jPasswordField3);
        jPasswordField3.setBounds(210, 150, 160, 18);

        jPasswordField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(210, 110, 160, 18);

        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(210, 70, 160, 18);

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 30, 160, 18);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Reset Password");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(99, 218, 158, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\java\\library_system\\images\\project\\solution-suite-customer.png")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-110, -40, 620, 400);

        setBounds(0, 0, 434, 329);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!jTextField1.getText().equals("") && !jPasswordField1.getText().equals(""))
        {
            if(jPasswordField2.getText().equals(jPasswordField3.getText()))
            {
                try
                {
                    Connection myconnection=DriverManager.getConnection(path+place,uname,password);
                    try
                    {

                        String q2="select uname from utable where uname=? and password=?";
                        PreparedStatement mystatement2=myconnection.prepareStatement(q2);
                        mystatement2.setString(1, jTextField1.getText());
                        mystatement2.setString(2, jPasswordField1.getText());
                        ResultSet myresult2=mystatement2.executeQuery();
                        if(!myresult2.next())
                        {
                            JOptionPane.showMessageDialog(null, "Username or password does not exist.\nKindly enter correct username and password.");
                            jTextField1.setText("");
                            jPasswordField1.setText("");
                        }
                        else
                        {
                            String q="update utable set password=? where uname=?";
                            PreparedStatement mystatement=myconnection.prepareStatement(q);
                            mystatement.setString(2, jTextField1.getText());
                            mystatement.setString(1, jPasswordField2.getText());
                            if(mystatement.executeUpdate()>0)
                            {
                                JOptionPane.showMessageDialog(null, "Password has been reset.");

                            }
                            jTextField1.setText("");
                            jPasswordField1.setText("");
                            jPasswordField2.setText("");
                            jPasswordField3.setText("");
                        }
                    }
                    catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null, "Error Establishing Query " + e.getMessage());
                    }
                    finally
                    {
                        myconnection.close();
                    }
                }
                catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null, "Error Establishing Connection " + e.getMessage());
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Password does not match.");
                jPasswordField1.setText("");
                jPasswordField2.setText("");
                jPasswordField3.setText("");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please enter valid username and password");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
