/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package library_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ESHA
 */
public class searchBook extends javax.swing.JInternalFrame implements commoninterface{

    /**
     * Creates new form searchBook
     */
    public searchBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Searching a Book");
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Name", "Book Id", "Author", "Publisher"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 97, 760, 290);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(84, 24, 189, 20);

        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(22, 27, 60, 14);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(324, 23, 110, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\java\\library_system\\images\\project\\gekleurde-boeken-op-achtergrond-4060368.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-290, -100, 1150, 730);

        setBounds(0, 0, 828, 628);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
       {
           Connection myconnection=DriverManager.getConnection(path+place,uname,password);
           if(!jTextField1.getText().equals(""))
           {
                try
                {

                    DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
                    String q="select * from books where name like ?";
                    PreparedStatement mystatement=myconnection.prepareStatement(q);
                    mystatement.setString(1, "%"+jTextField1.getText()+"%");
                    ResultSet myresult=mystatement.executeQuery();
                    mymodel.setRowCount(0);
                    if(myresult.next())
                    {
                        do
                        {    String name1,bookid1,author1,publisher1;
                             name1=myresult.getString("name");
                             bookid1=myresult.getString("book_id");
                             author1=myresult.getString("author");
                             publisher1=myresult.getString("publisher");
                      
                             mymodel.addRow(new Object[]{name1,bookid1,author1,publisher1});
                        }while(myresult.next());
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "Name does not exist.");
                        jTextField1.setText("");
                        
                    }          
                }
                catch(Exception e)
                {
                       JOptionPane.showMessageDialog(rootPane, "Error Establishing Query " + e.getMessage());
                }
                finally
                {
                       myconnection.close();
                }   
           }
           else
           {
               JOptionPane.showMessageDialog(rootPane, "Enter a valid name");
           }
       }
       catch(SQLException e)
       {
             JOptionPane.showMessageDialog(rootPane, "Error Establishing Connection " + e.getMessage());
       }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
